### ISSUE TITLE
`ScriptLookups` implementation

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#122]
- [ ] Similar to #101, we should add an implementation of Plutus' [`ScriptLookups`](https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger-constraints/html/Ledger-Constraints.html#t:ScriptLookups)
- [ ] With `ScriptLookups` in place, it's possible to implement `processConstraint`

**Comment by vvtran** [comment]
Started `Constraints` API  so may as well take this as it's closely related.
