### ISSUE TITLE
Slot BigInt (plutus) vs Slot(UInt32) (cardano-serialization-lib)

### ISSUE THREAD

**Issue by adamczykm** [Plutonomicon/cardano-browser-tx#124]
Which should we follow in general? Isn't 'lower bound' the safer way here?

> Why change from `BigInt` to `UInt`? The Plutus `Slot` is a wrapped `Integer`

_Originally posted by @ngua in https://github.com/Plutonomicon/cardano-browser-tx/pull/111#discussion_r808668313_

**Comment by ngua** [comment]
I think if there is a conflict we should generally defer to CSL

**Comment by ngua** [comment]
It looks like we've settled on using a wrapped `UInt` for this
