### ISSUE TITLE
numbers or adt enums as ffi to number based enums

### ISSUE THREAD

**Issue by adamczykm** [Plutonomicon/cardano-browser-tx#125]
Cardano-serialization-library exposes enums as numbers in its API should we stick to it or prepare our own ADT enums? First results in less code and conversion latter in PS native feel and no smart ctors.

> I liked the previous representation of `NetworkTag`, what was the reason for this change? In the functions that return a `BaseAddress` below, couldn't `netTagToInt` be used?

_Originally posted by @ngua in https://github.com/Plutonomicon/cardano-browser-tx/pull/111#discussion_r808670183_

**Comment by klntsky** [comment]
ADTs give totality check, while numbers do not. I believe that's a strong enough argument. Plus, in case of NetworkTag, it's instantly clear what we are dealing with when it's enum. How do I know there are the only two possible values when it's something else (just by looking at the definition, not at how it's used)?

**Comment by ngua** [comment]
I agree with @klntsky. There are only two valid network IDs and we can actually represent this, unlike on the JS side

**Comment by adamczykm** [comment]
Okay then. Any other instances of a similar approach? I can do a bulk change.

**Comment by ngua** [comment]
Closed by #129
