### ISSUE TITLE
Decode `ogmios-datum-cache` JSON responses

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#127]
[Here](https://github.com/mlabs-haskell/ogmios-datum-cache#getdatumbyhash) is an example response showing how the datums are encoded in the jsonwsp response

**Comment by ngua** [comment]
@klntsky Do you think you could take care of this?

**Comment by klntsky** [comment]
@ngua Yep.

**Comment by ngua** [comment]
Closed by #150

**Comment by ngua** [comment]
Closed by #150
