### ISSUE TITLE
Error when submitting transaction

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#134]
#121 enables transaction-submission capabilities to `QueryM`. Valid transactions with inputs from wallet addresses now work, but an exception is generated somewhere in `QueryM`. It appears that the WS interface attempts to parse a message but fails after the transaction is submitted. The errors

```
Uncaught TypeError: Cannot read properties of undefined (reading 'then')
    at eval (Promise.js?d439:22)
    at eval (Effect.js?a817:12)
    at eval (Effect.js?a817:12)
    at runAsync (Aff.js?357f:98)
    at run (Aff.js?357f:333)
    at eval (Aff.js?357f:348)
    at drain (Aff.js?357f:120)
    at Object.enqueue (Aff.js?357f:141)
    at eval (Aff.js?357f:339)
    at eval (Promise.purs?4dfa:28)
```
At first I thought this was a bug with Nami, but it appears to in fact be generated in the `QueryM` FFI module, specifically in
```js
// _onWsMessage :: WebSocket -> (String -> Effect Unit) -> Effect Unit
exports._onWsMessage = ws => fn => () => {
  ws.addEventListener('message', function func(event) {
    const str = event.data;
    console.log("message: ", str);
    fn(str)(); // here
  });
};
```
To reproduce: run the `Pkh2Pkh` example module

**Comment by klntsky** [comment]
That was probably introduced in #80.

What is the output of `console.log` call above?

**Comment by adamczykm** [comment]
I'm not experiencing the issue with the HEAD at `ee9e89bcce5f42fd7c141a1c25bcb06555cdf33a`

**Comment by ngua** [comment]
I just checked `ee9e89b` and the example works fully. The bug was introduced in `6a495ce`

**Comment by ngua** [comment]
Just to double-check, I created a new branch from master and checked out `Types.Value` at `ee9e89b` (i.e. before the recent changes). The example still works

**Comment by ngua** [comment]
@vvtran In that screenshot, did you close the signing prompt without signing it? That is the type of error you'd get

**Comment by vvtran** [comment]
I just pulled latest `master` so `79a3cf2fff70a2ce1acc77b8526d6bda01a55b0b` and my first attempt produced the same error message (from the first screenshot), I tried a few more times (refreshing each time) and I've been able to produce the tx hash each time 
![Uploading Screenshot from 2022-02-24 06-18-03.png…]()

**Comment by vvtran** [comment]
I'm fairly sure I didn't close it to reproduce the bug initially.

**Comment by vvtran** [comment]
Going back to `ee9e89b` specifically, I have the same error that was flagged up by this issue
![Screenshot from 2022-02-24 06-31-02](https://user-images.githubusercontent.com/81221015/155470558-18ca4929-7bd4-460b-ae75-9b09c117d29d.png)

**Comment by vvtran** [comment]
It seems like everytime I change branches,  go back into `nix develop`, my initial run produces the `couldn't extract JS error or string` error, then it turns into the bug of this issue (e.g. from `ee9e89b`) or in the latest `master`, is fixed and produces tx hash.

**Comment by vvtran** [comment]
It seems like everytime I change branches,  go back into `nix develop`, my initial run produces the `couldn't extract JS error or string` error, then it turns into the bug of this issue (e.g. from `ee9e89b`) or in the latest `master`, is fixed and produces tx hash.

**Comment by vvtran** [comment]
Checked out to `ee9e89bcce5f42fd7c141a1c25bcb06555cdf33a` and that worked first go, I wonder if that PR fixed the issue for some of us (intentionally or not).

@ngua is it possible to have a browser dependency issue?

**Comment by ngua** [comment]
Well, this is really bizarre. Just checked out master again and it seems to be working. Guess we can close this
