### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-browser-tx#14]
once we have testing frameworks in place (https://github.com/Plutonomicon/cardano-browser-tx/issues/13), we'll want some CI checks, namely:

- no compiler warnings
- the package builds and passes tests

**Comment by Benjmhart** [comment]
let's get Purty checks here as well.

perhaps nixfmt?

**Comment by Benjmhart** [comment]
ideally each ci job has a makefile script that runs them inside the nix shell.

we should also be sure to set up cachix.

**Comment by Benjmhart** [comment]
this can use github actions

**Comment by ngua** [comment]
It seems like the Hercules instance is working fine for the build. We have #57 as well for formatting so I think we can close this
