### ISSUE TITLE
Define `unitRedeemer` and `unitDatum`

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-browser-tx#147]
`unitRedeemer :: RedeemerTag -> Redeemer` currently in `Types.PlutusData` should be defined as we may need an equivalent to https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger/html/Ledger.html#v:unitRedeemer in Haskell, defined as 
```
-- | @()@ as a datum.
unitDatum :: Datum
unitDatum = Datum $ toBuiltinData ()

-- | @()@ as a redeemer.
unitRedeemer :: Redeemer
unitRedeemer = Redeemer $ toBuiltinData ()
```
where our `toBuiltinData` is `toData` from `class ToData`. Our `Redeemer` type has a few other fields like `index` and `ex_units` which would somehow need filling. These are used in the `Constraints` API when the user wants to mint tokens with a unit redeemer for example.

`unitDatum` should be easier once we can convert to `unit` to `PlutusData`.

**Comment by ngua** [comment]
If I'm not mistaken, this is really two different (if related) issues: 

- We need `ToData` instances not just for `unit` but for various common types
- We need to figure out a way to convert between the type of redeemer encountered in off-chain code (which is just `newtype`d `Data`) and the CSL's representation of a redeemer

@klntsky How are you planning on approaching this issue?

**Comment by ngua** [comment]
The second part of my message above will be taken care of in #148. I think it's best to write instances for common types for this issue
