### ISSUE TITLE
Custom PS prelude for library users

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#154]
I was thinking it might be nice to support a custom Purescript prelude for our users

Rationale:
- The PS prelude exports far less than its Haskell counterpart. This might increase friction as users try to port their off-chain code
- We can select certain common (non-`Prelude`) types/functions to re-export that differ from what a Haskell developer might reasonably expect (e.g. `Data.Semigroup.Last` vs `Data.Maybe.Last`)
- We can also export effects, types, etc... that almost all off-chain code uses

**Comment by Benjmhart** [comment]
this is nice to have, especially as a guideline for your default number types.

**Comment by Benjmhart** [comment]
it may cause a problem with purescript-bridge shimming though, unless we have an equivalent prelude in haskell....
