### ISSUE TITLE
Add Ogmios' `chainTip` to `QueryM` (to replicate `currentSlot` function)

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-browser-tx#169]
As part of the script lookups PR https://github.com/Plutonomicon/cardano-browser-tx/pull/148, we replicated most of the `TimeSlot` module with the exception of `currentSlot` https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger/html/Ledger-TimeSlot.html#v:currentSlot. There is a placeholder for this in `Types.Interval` `currentSlot :: SlotConfig -> Effect Slot`.

**Comment by ngua** [comment]
Ogmios to the rescue again: we can use the `chainTip` local state query to get the current slot (https://ogmios.dev/mini-protocols/local-state-query/#query)

The response will look like this:

```json
"PointOrOrigin":
    { "oneOf":
      [ { "type": "object"
        , "description": "A point on the chain, identified by a slot and a block header hash."
        , "title": "point"
        , "additionalProperties": false
        , "required": [ "slot", "hash" ]
        , "properties":
          { "slot": { "$ref": "#/definitions/Slot" }
          , "hash": { "$ref": "#/definitions/Digest[Blake2b]::Block[*].header" }
          }
        }
      , { "$ref": "#/definitions/Origin" }
      ]
    }

  , 
```
