### ISSUE TITLE
Create types from `PlutusTx` e.g. `Rational`, `Natural` for Purescript bridge

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-browser-tx#180]
Need to recreate as many types as possible from https://github.com/input-output-hk/plutus/tree/master/plutus-tx/src/PlutusTx
most of these are already available in Purescript
- Current standout is probably `Ratio`, we should probably create a custom type as `Data.Rational` is limited by `Int`, and we'd prefer `BigInt`.
- We may need a `Natural` type too. This is probably more related to `plutus-extra`.

**Comment by klntsky** [comment]
I'm going to add `Ratio` as well.
