### ISSUE TITLE
successfully call Nami wallet with a 'simple' handcrafted transaction (no plutus)

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-browser-tx#2]

**Comment by Benjmhart** [comment]
blocked on https://github.com/Plutonomicon/cardano-browser-tx/issues/5 currently

**Comment by Benjmhart** [comment]
some additional status:

presently we have the type for a transaction built,  so we need to query the chain to get the TxInputs needed, such that we can create a valid transaction.

once this step is complete, we will try to sort out the best way to provide signing options in-and-out of the browser (in-browser you will want to use Nami, out of browser you will want to invoke the wallet-backend process.

**Comment by ngua** [comment]
Waiting for #32 to be merged, this will be simplified considerably (and will avoid code duplication) by having a common set of serialization-lib bindings

**Comment by ngua** [comment]
I'm going to close this in favor of more specific issues (#64, #63)
