### ISSUE TITLE
Remove `ScriptHash`-related code from `Types.ScriptLookups`

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#203]
The current implementation of `Scripts.plutusScriptHash` (and anything that relies on it) is broken. It eventually calls CSL's `ScriptHash.from_bytes()` using the CBOR-encoded bytes of the Plutus script, but this method is only for CBOR-encoded script hashes themselves, not scripts

There doesn't appear to be a way to hash Plutus scripts using CSL, so the current lookups won't work. The fastest way to fix this is to change how the lookups work internally (e.g. change `mps` and `otherScripts` in `ScriptLookups`)

We also need to fix how to hash different types of scripts (see #204) correctly

**Comment by vvtran** [comment]
https://github.com/Plutonomicon/cardano-browser-tx/pull/207
