### ISSUE TITLE
Datum and datum hash is incorrect when submitting

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#219]
It appears that datum hashing fails. Trying to submit with datums results in:

```
"transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (NonOutputSupplimentaryDatums (fromList [SafeHash \"923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec\"]) (fromList [])),UtxowFailure (PPViewHashesDontMatch SNothing (SJust (SafeHash \"2f50ea2546f8ce020ca45bfcf2abeb02ff18af2283466f888ae489184b3d2d39\")))])"
```

To reproduce, run `npm run dev` on the `rory/submit-with-datums` branch

**Comment by ngua** [comment]
I think we can just upgrade the version/fork of CSL that we're using

**Comment by ngua** [comment]
The current strategy is to use the backend for this by sending the partially complete transaction along with its datums and redeemers to be processed directly in Haskell. According to @klntsky, the hashes are still reported as incorrect when the built transaction is submitted

I think at least part of the issue is that we are serializing the datums and redeemers to CBOR on the frontend. This is much faster to implement than serializing them to JSON, but I think we need to use the latter to avoid and serialization issues with CSL. I think we should use the following approach to solve this:
- write `EncodeJson` instances on the frontend for `PlutusData` and `Types.Transaction.Redeemer`. Send these JSON encodings to the backend along with the CBOR tx, instead of the CBOR as we currently do
- write a `FromJSON` instance for corresponding types on the backend (probably a newtype wrapper for `Data`; we will have to define a type corresponding to our `Redeemer` and then write an instance for it)
- replace the datums and redeemer serialized to CBOR in `FinalizeRequest` with the datums and redeemers serialized to JSON
- we will have the datums at this point, but we will need to convert the redeemers to the Alonzo `Redeemers` type, which is just a `Map RdmrPtr (Data era, ExUnits)`, using the `Redeemers'` pattern synonym
- calculate the hashes for the rest of the tx as we are doing now

**Comment by klntsky** [comment]
@ngua Is it _confirmed_ that cbor serialization on frontend is a problem? I mean, do we have a particular example of `PlutusData` that is encoded on the frontend differently from a similar value encoded on backend?

**Comment by klntsky** [comment]
I have checked that at least for `plutusDataFixture6` server-side encoding matches client-side.

**Comment by ngua** [comment]
Fixed on seabug-deployment
