### ISSUE TITLE
nix develop

### ISSUE THREAD

**Issue by weskinner** [Plutonomicon/cardano-browser-tx#225]
In order to run `nix develop` I had to run ` nix --extra-experimental-features nix-command --extra-experimental-features flakes develop`.  Should the readme include these flags?

**Comment by ngua** [comment]
To avoid having to pass those flags each time you use a flakes-based project, you can add the following to your `nix.conf` (this could be in `/etc/nix/nix.conf` or `~/.config/nix/nix.conf`, or elsewhere depending on your system):

```
experimental-features = nix-command flakes
```
We could clarify that we use flakes in the readme and suggest users to either pass the flags or enable them in their configuration

**Comment by ngua** [comment]
I've added a note to the readme in #287
