### ISSUE TITLE
Full NFT metadata for Seabug query endpoint

### ISSUE THREAD

**Issue by nrutledge** [Plutonomicon/cardano-browser-tx#239]
When the Seabug frontend fetches the list of NFTs via CTL query, all of the metadata fields should be returned. This data is required in order to relate each NFT to the corresponding off-chain image/artist, display NFT info in the UI, and later pass the required params to the buy "endpoint".

Required Fields:
- `ipfsHash`
- `collectionNftCS`
- `collectionNftTN`
- `lockingScript`
- `authorPkh`
- `authorShare`
- `marketplaceScript`
- `marketplaceShare`
- `ownerPkh`
- `ownerPrice`

In metadata but may not be required (include anyway):
- `mintPolicy`

The following fields are required params for the buy endpoint but are not in the metadata (need to sort these ones out):
- `lockLockup`  - can buy params be changed to not require this?
-  `lockLockupEnd` - can buy params be changed to not require this?
- `daoScript` - is this same as `marketplaceScript` metadata field?
- `daoShare` - is this same as `marketplaceShare` metadata field?

**Comment by t4ccer** [comment]
> daoScript - is this same as marketplaceScript metadata field?
daoShare - is this same as marketplaceShare metadata field?

Yes

**Comment by t4ccer** [comment]
> lockLockup - can buy params be changed to not require this?
lockLockupEnd - can buy params be changed to not require this?

I believe that these are used only for minting/burning, and record that required these fields was used for convenience

**Comment by vvtran** [comment]
Would it be possible to add the `author` (without the `payment` prefix) from the `NFTData.NFTCOllection` into a field of `MarketplaceDatum`  as `authorPkh` during the buy end point as a temporary solution? This doesn't prevent people from sending garbage into this field though so some checks may be needed. This would likely affect how validation works @nrutledge @t4ccer

**Comment by vvtran** [comment]
Actually ignore, I think I may have misunderstood something. The buy end point comes later.

**Comment by ngua** [comment]
The Seabug branches now support querying with both the Seabug-style metadata and the IPFS hash
