### ISSUE TITLE
applyCode

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-browser-tx#24]
we're going to need to be able to apply arguments to scripts and get the correct resulting hash

example: if a project uses a script that is parameterized over someone's pubkeyhash, then we will need a different version for each pubkey that might need to interact with our dApp.

ideally, we should be working with the stringified, non-CBOR version of the script, and hopefully we can get away with minimal parsing and string manipulation, rather than building out an AST.

we need examples of un-applied and applied scripts to see how to do this properly.

in a worst case scenario we could make this a backend service.

**EDIT**:

Since we are using the Haskell server for this, there are really two tasks:
- [x] Call `applyArgs` on the server and respond with the applied script
- [x] Add a `QueryM` effect to call this on the client side

**Comment by mikekeke** [comment]
To get unapplied and applied PLC[ EfficientNFT validator](https://github.com/mlabs-haskell/plutus-use-cases/blob/3b7a2bc6bcb1d5ce02a7c99d3c2bdce646f95b47/mlabs/src/Mlabs/EfficientNFT/Marketplace.hs#L24-L41) was used.

Here are results (content of files with `_space_to_nl` is same as w/o suffix, just spaces replaced with newlines to make sort of formatting for easier side-by-side comparison):
[plc_unapplied.txt](https://github.com/Plutonomicon/cardano-browser-tx/files/7887296/plc_unapplied.txt)
[plc_applied.txt](https://github.com/Plutonomicon/cardano-browser-tx/files/7887297/plc_applied.txt)
[plc_unapplied_space_to_nl.txt](https://github.com/Plutonomicon/cardano-browser-tx/files/7887299/plc_unapplied_space_to_nl.txt)
[plc_applied_space_to_nl.txt](https://github.com/Plutonomicon/cardano-browser-tx/files/7887300/plc_applied_space_to_nl.txt)

(Just in case, code snippet which was used to obtain plc)
```
run :: Hask.IO ()
run = do
  let unapplied = $$(PlutusTx.compile [||mkValidator||])
      applied = unapplied `PlutusTx.applyCode` PlutusTx.liftCode (Value.CurrencySymbol  "ff")

  Hask.writeFile "./plc_unapplied" (toPlcString unapplied)
  Hask.writeFile "./plc_applied" (toPlcString applied)

  where
    toPlcString = Hask.show . PluttusTx.getPlc
```

**Comment by mikekeke** [comment]
Found that it can be pretty printed also, so here are pretty variants as well:
[pretty_unapplied.txt](https://github.com/Plutonomicon/cardano-browser-tx/files/7887614/pretty_unapplied.txt)
[pretty_applied.txt](https://github.com/Plutonomicon/cardano-browser-tx/files/7887616/pretty_applied.txt)

**Comment by t1lde** [comment]
A complication to note in relation to this wrt. Plutarch -

so, afaik, params with `applyCode` in plutus-tx will create an Apply term:

```haskell
applyProgram
    :: Monoid a
    => Program tyname name uni fun a
    -> Program tyname name uni fun a
    -> Program tyname name uni fun a
applyProgram (Program a1 t1) (Program a2 t2) = Program (a1 <> a2) (Apply mempty t1 t2)
```

which is pretty simple. 

Plutarch scripts *can* use `applyCode` compatibly, however it could be that the params are complex (or involve metaprogramming) and we'd prefer to inline them, so instead of using `applyCode`, we'd use `plet`, or provide the parameterized script as a function returning a plutarch AST... so the story for 'dynamic' parametrized scripts is more complex (definitely requiring a backend service, and the complexities of 'trusting' the result).

**Comment by mikekeke** [comment]
As @zygomeb requested:
For [this minting policy](https://github.com/mlabs-haskell/plutus-use-cases/blob/3b7a2bc6bcb1d5ce02a7c99d3c2bdce646f95b47/mlabs/src/Mlabs/EfficientNFT/Token.hs#L41-L50):
[policy_unapplied.txt](https://github.com/Plutonomicon/cardano-browser-tx/files/7888755/policy_unapplied.txt)
[policy_oref_applied.txt](https://github.com/Plutonomicon/cardano-browser-tx/files/7888756/policy_oref_applied.txt)
[policy_all_applied.txt](https://github.com/Plutonomicon/cardano-browser-tx/files/7888757/policy_all_applied.txt)

**Comment by ngua** [comment]
Back to stage 3 as this is required by Seabug
