### ISSUE TITLE
Correct implementation to get an `Address` from `ScriptHash`

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-browser-tx#243]
Related to https://github.com/Plutonomicon/cardano-browser-tx/issues/242 I'll copy and paste some of the issue over:

`PublicKey` is a newtype wrapper over Bech32String which is an alias of `String`, the issue is the string can be different lengths so some further newtype wrappers over String would probably make sense (see above issue)

For example, we can use `ed25519KeyHashFromBech32 :: Bech32String -> Maybe Ed25519KeyHash` on an input like `"addr_vkh1zuctrdcq6ctd29242w8g84nlz0q38t2lnv3zzfcrfqktx0c9tzp"` but not
`"addr1qyc0kwu98x23ufhsxjgs5k3h7gktn8v5682qna5amwh2juguztcrc8hjay66es67ctn0jmr9plfmlw37je2s2px4xdssgvxerq"`. However,
we can use `addressBech32 :: Address -> Bech32String` on the latter.

I believe this is because the former being an enterprise address (no staking credentials), and hence shorter. Feel free to correct my understanding on this.

The issue here is we can't get an `Address` from a `ScriptHash` (i.e. `ValidatorHash` contained in a `TypedValidator a`). Our currently implementation 
`typedValidatorAddress :: forall (a :: Type). NetworkId -> TypedValidator a -> Address` goes via the `BaseAddress`. This seemingly always produces  an address with stake credentials. Perhaps we need to reconsider and go via `EnterpriseAddress` which is an `Address` without staking credentials.

This mirrors the `Maybe` type in the definition of Plutus' `Address`
https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger/html/Ledger-Address.html#t:Address

**Comment by vvtran** [comment]
Can we close this with our enterprise address implementation?

**Comment by vvtran** [comment]
Or perhaps switch to "bug" as we would need to do cherry-pick commits over to master.

**Comment by ngua** [comment]
Changed to a "bug" since we need to apply the changes to master as well

**Comment by ngua** [comment]
Fixed on Seabug branch, will merge into master soon
