### ISSUE TITLE
Currency symbol and token name generated by buy end point aren't matching those at script address

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-browser-tx#247]
- The currency symbol (from applying minting policy then taking curr symbol) and token name (generated by blake2b) aren't matching those at the utxos address `addr_test1wr05mmuhd3nvyjan9u4a7c76gj756am40qg7vuz90vnkjzczfulda` https://testnet.cardanoscan.io/address/70df4def976c66c24bb32f2bdf63da44bd4d77757811e670457b27690b
- It was spotted that the apply arguments was being applied to too many arguments in the wrong order which has been fixed locally - although the curr symbol is still wrong.
- Investigate relevant `ToData` and `DecodeJson` instances.
- Investigate `Types.Value.mpsSymbol` which is implicitly used to convert a minting policy hash to currency symbol.

Any ideas welcome.

**Comment by vvtran** [comment]
Changed `lockingScript` (hexastring) to be `6c1039b6973bb0e7ad42de5b16a691ede3e0265cd58caf070ff15ef3` and that changes the currency symbol of course, but it's still not correct.

**Comment by ngua** [comment]
OK, this currency symbol issue is almost certainly because of the same underlying thing that causes #189

The token name has been fixed, so I'm going to close this
