### ISSUE TITLE
TypeScript types for Seabug SDK

### ISSUE THREAD

**Issue by nrutledge** [Plutonomicon/cardano-browser-tx#279]
The Seabug SDK currently lacks any types:
https://github.com/Plutonomicon/cardano-browser-tx/blob/seabug-deployment/npm-packages/cardano-transaction-lib-seabug/index.js

It would be ideal if this were a TypeScript file with the types for parameters and return values defined.

**Comment by ngua** [comment]
Implemented on seabug-deployment
