### ISSUE TITLE
add `purty` autoformat script

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-browser-tx#28]

**Comment by paluh** [comment]
Maybe it would be better to just use `purs-tidy` from the beginning - we can say that it is a de facto standard formatting tool for PS right now ( `purty` has not been updated to the latest PS version. ). Here is an example config from [purescript-contrib/purescript-parsing](https://github.com/purescript-contrib/purescript-parsing/blob/main/.tidyrc.json).

**Comment by adamczykm** [comment]
Cześć @paluh

**Comment by ngua** [comment]
This is taken care of by #52
