### ISSUE TITLE
Fix name and add a LICENSE file

### ISSUE THREAD

**Issue by adamczykm** [Plutonomicon/cardano-browser-tx#281]
Currently the package name proudly states "realpab @ 1.0.0". I think we should stick to cardano-transaction-lib at 0.1.0.

Also, the repository lacks a LICENSE file so we should pick one. Will **ISC** be okay? @Benjmhart  @ngua 

> A permissive license lets people do anything with your code with proper attribution and without warranty. The ISC license is functionally equivalent to the [BSD 2-Clause](https://choosealicense.com/licenses/bsd-2-clause/) and [MIT](https://choosealicense.com/licenses/mit/) licenses, removing some language that is no longer necessary.

The github repository name should be corrected as well.

**Comment by ngua** [comment]
Our open-source policy recommends MIT or Apache, so we should go with one of those

There are a number of other places where we use the old name as well. We should change those too

**Comment by adamczykm** [comment]
updated the pr
