### ISSUE TITLE
JSON / BigInt preprocessor

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-browser-tx#29]
haskell serializes arbitrary-precision numbers as Integers.

when javascript decodes them as IEEE Floats, we can lose precision.

the `argonaut` library can't really be used here since it converts all json values into JS values and THEN parses them to PS values.

so we need to roll over json as a string, and whenever we encounter an integer larger than 32 bits, wrap it in quotes so it can be parsed correctly as a BigInt.

**Comment by adamczykm** [comment]
So in jsons we get from outside we expect values such as: `{"bigint": 1000000000000000}`?

**Comment by adamczykm** [comment]
I see here two options.
First is to provide custom JSON parser and then come up with a way to decode it to a custom types based on existing libraries or fork existing library injecting our custom parser (easy for the `simple-json` lib).
Second will be to replace all numbers in JSON for strings and then parse it as such as with existing solutions, decoding BigInts at the end of the pipeline.
Which should I pursue?

**Comment by Benjmhart** [comment]
honestly replacing all numbers in json for strings and then parse it with existing solutions is what i had in mind.

**Comment by Benjmhart** [comment]
> Doesn't it use doubles?
> 
> ```js
> > Number.MAX_VALUE
> 1.7976931348623157e+308
> > Number.MAX_SAFE_INTEGER
> 9007199254740991
> ```

yeah, IEEE Double-precision Floating point numbers,
