### ISSUE TITLE
Fee Estimation function

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-browser-tx#36]
we need a function to estimate fees, this will be easiest to use a haskell server for now

**Comment by vvtran** [comment]
If you are happy with an  **estimation**, there is this (deprecated) function https://input-output-hk.github.io/cardano-node/cardano-api/src/Cardano.Api.Fees.html#estimateTransactionFee which requires
- The number of extra UTxO transaction inputs
- The number of extra transaction outputs
- The number of extra Shelley key witnesses
- The number of extra Byron key witnesses
Is this info these available to us? See also `attributes` which is a CBOR serialisation.

**Comment by vvtran** [comment]
Admittedly I'm not sure how reliable this actually is, but it does potentially provide an option for purescript only, given it's only an estimate.
