### ISSUE TITLE
`UnbalancedTransaction`

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#37]
Create an `UnbalancedTransaction` type (e.g. [here](https://github.com/input-output-hk/plutus-apps/blob/901bbad3ab1c64c8b5d0b5a5fb3e7362e38e8848/plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs), note that recent plutus-apps splits `PubKeyHash` into a few different newtypes). Since we want to replicate the constraints API from `Contract` the type should match the plutus one pretty closely

**Comment by vvtran** [comment]
Once https://github.com/Plutonomicon/cardano-browser-tx/pull/22 gets merged in, you'll noticed a placeholder type for this in `balanceTx.purs`, feel free to create outside of this type so you don't have to deal with type errors from the balancer and we can glue back later.
