### ISSUE TITLE
Get private keys for transaction signing

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-browser-tx#48]
- In MLabs pab, a `Map PubKeyHash PrivateKey` is obtained for signing the transaction. We need something similar like `Map Address PrivateKey`, there is currently a placeholder newtype `PrivateKey` in the `BalanceTx`.

**Comment by ngua** [comment]
This won't be possible with a browser-based wallet, but that's OK since we will be using the wallet directly for signing. Nami's `signTx` will return a `TransactionWitnessSet` which we can then add to the transaction itself
