### ISSUE TITLE
Write tx signing functionality

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-browser-tx#49]
We need something similar to `Tx.addSignature` https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger/html/Ledger-Tx.html#v:addSignature to replace `signBy` in `BalanceTx`, also need to determine how signing works for our transaction type, whether sign `TxBody` or `Transaction`.

Related issue: https://github.com/Plutonomicon/cardano-browser-tx/issues/48

**Comment by ngua** [comment]
This will need to be taken care of by the wallet (e.g. nami)

**Comment by vvtran** [comment]
Cool.

**Comment by klntsky** [comment]
Should we close this?

**Comment by vvtran** [comment]
Closing.
