### ISSUE TITLE
For consideration: Move reencoding of json to Haskell side.

### ISSUE THREAD

**Issue by adamczykm** [Plutonomicon/cardano-browser-tx#53]
What if we re-parsed and re-encoded the jsons on haskell side just before sending them to frontend? I mean a thin layer in front of ogmios?
 
Apparently we should be able to traverse the jsons without the need to know the datatype schema that was used to generate them. The advantage is that we would be dealing with already-parsed jsons (as a tree structure), which is more reliable than a custom state machine-based tokenizer of string.

@ngua

_Originally posted by @klntsky in https://github.com/Plutonomicon/cardano-browser-tx/pull/34#discussion_r791672366_

**Comment by Benjmhart** [comment]
let's discuss, but fundamentally i'm against sending JSON to haskell just to parse & reformat. can we perhaps have a call about the difficulty?

**Comment by klntsky** [comment]
@Benjmhart the idea is to alter JSON *before* sending it to frontend.

**Comment by Benjmhart** [comment]
oh, so this would be a change to ogmios @klntsky @adamczykm ?

**Comment by klntsky** [comment]
@Benjmhart Either a change to ogmios or a new binary that uses it as library and re-defines its API handlers.

**Comment by ngua** [comment]
I think our JSON re-encoding woes have been addressed pretty thoroughly in #150. I'm going to close this for now, feel free to reopen later if necessary
