### ISSUE TITLE
Implement core of Nami wallet interface

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#64]
While we don't need to implement all of Nami's functionality, we do need FFI wrappers around at least the following to build an `UnbalancedTx` as part of our first goal:

**NOTE**: Some of the links below are for the deprecated `window.cardano` injected API. This is because there are no docs for the new injected API; the parameters and return values are the same for the examples below, however, so I linked to them for convenience

- [x] `enable` (https://github.com/Berry-Pool/nami-wallet#cardanoenable) -- **WORKING** 
- [x] `getUsedAddresses` (https://github.com/Berry-Pool/nami-wallet#cardanogetusedaddresses; note that Nami only has a single address per wallet but returns an array to follow the CIP) -- **WORKING**
- [x] `getCollateral` (https://github.com/Berry-Pool/nami-wallet#apiexperimentalgetcollateral) -- **WORKING** 
- [x] `signTx`. Nami actually returns a `TransactionWitnessSet`, but it probably makes more sense to have the action as follows for ease of use
  ```purescript
  signTx :: Transaction -> Aff Transaction
  ``` 
  In this case `signTx` will add the new, returned witness set to the existing transaction

All of these return an `Effect (Promise ...)` which we can then lift into `Aff` (i.e. `Control.Promise.toAffE`. Most of them return a hexadecimal string which needs to be decoded

Related issues/PRs: #60, #31, #44, #49

**Comment by klntsky** [comment]
So for `getCollateral` we need to work with `TransactionUnspentOutput` (i.e. being able to de-serialize it). Should I create a task to add this type?

**Comment by klntsky** [comment]
As for de-serialization, we only need `BaseAddress` and `TransactionUnspentOutput` for now, right?

**Comment by ngua** [comment]
Yes, that's correct. I can create an issue, although I think we can just add the type and the deserialization in a single PR
