### ISSUE TITLE
Load different CSL packages depending on environment

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#69]
We need to figure out a way to either load the Node or browser version of CSL

**Comment by klntsky** [comment]
Looks like this thing is what we need: https://github.com/webpack/docs/wiki/list-of-plugins#defineplugin

If we want to build with nix, we can pass info to webpack config through environment variables.

**Comment by ngua** [comment]
Closed by #80

**Comment by ngua** [comment]
Closed by https://github.com/Plutonomicon/cardano-browser-tx/pull/80
