### ISSUE TITLE
create a `balanceTx` function

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-browser-tx#7]
there are general instructions on how to balance a tx here: https://docs.google.com/document/d/1B4CBCWETDOGkPtsWxgKZJx6yF_51rp1w35fNVaUQo3U/edit?usp=sharing

**Comment by blamario** [comment]
It's worth noting that the fee estimate that `balanceTx` performs depends on the number of expected signatories. See [this discussion](https://mlabs.slab.com/posts/transaction-multisign-procedure-i9r7eeyp) for detail.

**Comment by Benjmhart** [comment]
this PR https://github.com/mlabs-haskell/mlabs-pab/pull/24 implements a balancing function in Haskell.

**Comment by vvtran** [comment]
Can't self assign.

**Comment by vvtran** [comment]
Adding a haskell server label because this ticket requires transaction fee calculation. We could use estimates in the mean time as I believe these fees don't need to be exact.

**Comment by ngua** [comment]
Closed by #22 (and superseded by some additional issues like #75, #71 etc...)
