### ISSUE TITLE
Integration balancing with fee estimation and signing

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#71]
After #22 is merged, we will have a balancer with some placeholders remaining

We need to integrate various other parts of the project to complete the `UnbalancedTransaction -> Transaction` part

This includes
- [ ] signing: will be taken care of by #64
- [ ] fee estimation: taken care of by #55. We can just use manual HTTP requests for now. In the future we might be able to generate a client with `servant-purescript` though

**Comment by vvtran** [comment]
If you want, you can add https://github.com/Plutonomicon/cardano-browser-tx/issues/86 to the list.
