### ISSUE TITLE
Get websockets to work in the browser

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#74]
Apparently the `ws` package does not work in the browser (even when polyfilling the packages) and we need to use the browser-native `WebSocket` object instead

There are some packages like `isomorphic-ws`, but I don't think that's the best option

**Comment by ngua** [comment]
We'll have to think of a similar solution with this as with #69

**Comment by ngua** [comment]
We also need to remove the `options` arg from this line:
```js
const ws = new WebSocket(url, { perMessageDeflate: false });
```
This isn't supported by the browser

**Comment by klntsky** [comment]
This was done in #80 .
