### ISSUE TITLE
Write smart constructors for Value, TokenName and CurrencySymbol

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-browser-tx#75]
- With `Value` now defined as a product type of Ada and non-Ada assets, we should provide smart constructors to construct such terms. This should prevent mixing of lovelaces into the non-Ada asset map.
- We should remove the export of such data constructors.
- Remove any newtype instances that would allow us to construct via `wrap`.
- Reconsider what functions should be exported from `Types.Value` e.g. `flattenValue` - perhaps move to balancer and not export.
- See https://github.com/Plutonomicon/cardano-browser-tx/pull/84 and https://github.com/Plutonomicon/cardano-browser-tx/pull/97

**Comment by vvtran** [comment]
See comments by @ngua in https://github.com/Plutonomicon/cardano-browser-tx/pull/22

**Comment by klntsky** [comment]
> This should prevent mixing of lovelaces into the non-Ada asset map.

Note that something like `adaSymbol = CurrencySymbol mempty` is not serializable. I suggest making CurrencySymbol a smart constructor that checks the length.

**Comment by klntsky** [comment]
Validation can be done by calling serialization-lib.

**Comment by vvtran** [comment]
@klntsky I haven't used the CSL at all, is it more complicated than just checking the length > 0? Or are there helpers within CSL that can verify a `ByteArray`, or `Uint8Array` to be more precise, is a currency symbol - if so, do you have any pointers on this?

**Comment by klntsky** [comment]
ScriptHash [is defined](https://github.com/input-output-hk/cardano-ledger/blob/f2a783cf00911b7492e81dd6c7fb8a963f9ce8fe/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L385) as `hash28`.

**Comment by klntsky** [comment]
> are there helpers within CSL that can verify a ByteArray, or Uint8Array to be more precise, is a currency symbol - if so, do you have any pointers on this?

I believe you can only verify it by trying to construct it

**Comment by vvtran** [comment]
closing with https://github.com/Plutonomicon/cardano-browser-tx/pull/84 and https://github.com/Plutonomicon/cardano-browser-tx/pull/97
