### ISSUE TITLE
Potentially fix `datum` type for `OgmiosTxOut` in `Types.JsonWsp` 

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-browser-tx#78]
Currently
```
type OgmiosTxOut =
  { address :: Address
  , value :: Value
  , datum :: Maybe String
  }
```
and https://ogmios.dev/ogmios.wsp.json (see "datum") says datum is base64, although the example looks like a hexadecimal (this looks to be the hash of the datum in fact). We may need datum to be a sum type over both possibilities? ATM,`txOutRefToTransactionInput :: TxOutRef -> Maybe Transaction.TransactionInput` assumes it's a hexadecimal.

**Comment by ngua** [comment]
Have you spoken to @aske about this on the Ogmios side?

**Comment by ngua** [comment]
I don't believe this became an issue after all, so I think we can close this
